config/routes.rb
Rails.application.routes.draw do

  root                'questions#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'
  post   'upvote'  => 'votes#create'
  post   'downvote'=> 'votes#destroy'
  get    'best'    => 'answers#display_best'
  post   'best'    => 'answers#set_best'
  get    'vote'    => 'questions#vote'
  get    'trending'=> 'questions#trending'

  resources :users
  resources :questions
  resources :comments, only: [:new, :create]
  resources :answers
  resources :votes, only: [:new, :create, :destroy]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :source
  has_many :votes, as: :source


  def self.one_best(question_id)

    question = Question.find(question_id)
    best = question.answers.where(best: true)

    byebug
    if best == []
      false
    else
      true
    end


  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :source, polymorphic: true
  has_many :votes, as: :source

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :comments, as: :source
  has_many :votes, as: :source
  belongs_to :user
  has_many :answers

  def self.vote_count(question_id)

    question = Question.find(question_id)
    question.update(vote_count: question.votes.count)
  end

  def self.trending

    questions = Question.all
    questions.each do |q|
      q.update(trending: q.answers.where(created_at: (Time.now - 1.hour)..Time.now).count)
   end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

 def self.authenticate(username, password)

     @user = User.where(username: username, password: password).first
     # if email and password correspond to a valid user, return that user
     if @user.present?
       @user
     # otherwise, return nil
     else
       nil
     end
 end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :source, polymorphic: true

  def self.vote_only_once(user_id, source)
      @vote = Vote.where(user_id: user_id, source: source).first
      if @vote.present?
        return true

      else
        return false
      end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :set_answer, :only => [:show, :edit, :update, :destroy,]
  include SessionsHelper

  def new
    @answer = Answer.new
  end

  def create

    @question = Question.find(params[:answer][:question].to_i)

    @answer = Answer.create(text: params[:answer][:text], question: @question, user: current_user)


    redirect_to @question

  end

  def edit

  end

  def update

    @question = Question.find(params[:answer][:question].to_i)

    @answer.update(text: params[:answer][:text], question: @question, user: current_user)

    redirect_to


  end

  def display_best

   @user = current_user
   @questions = current_user.questions


  end

  def set_best

    @answer = Answer.find(params[:answer][:answer])

    byebug
    @question = @answer.question

    if Answer.one_best(@question.id)
      redirect_to best_path
    else
      @answer.update(best: true)
      byebug
      redirect_to best_path
    end

  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :set_comment, :only => [:show, :edit, :update, :destroy]
  include SessionsHelper



  def new
    @comment = Comment.new
  end

  def create

    @question = Question.find(params[:comment][:question].to_i)

    @comment = Comment.create(text: params[:comment][:text], source: @question, user: current_user)

    redirect_to @question
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end
end



# create_table "comments", force: true do |t|
#   t.text     "text"
#   t.integer  "source_id"
#   t.string   "source_type"
#   t.integer  "user_id"
#   t.datetime "created_at"
#   t.datetime "updated_at"

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    include SessionsHelper
    before_filter :set_question, :only => [:show, :edit, :update, :destroy]



    def index

      @questions = Question.order(updated_at: :desc)

    end

    def vote

      @questions = Question.order(vote_count: :desc)
      render 'questions/index'

    end

    def trending

        Question.trending
        @questions = Question.order(trending: :desc)
        render 'questions/index'

    end

    def show
        @comment = Comment.new
        @answer = Answer.new
        @vote = Vote.new
    end

    def new
        @question = Question.new
    end

    def create

        @question = Question.create(title: params[:question][:title], text: params[:question][:text], user: current_user)

        redirect_to questions_url

    end

    def edit

    end

    def update


        @question.update(title: params[:question][:title], text: params[:question][:text], user: current_user)

        redirect_to questions_url

    end


    def destroy
    end

    private
    def set_question
        @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :text)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new

  end

  def create
    @user = User.authenticate(params[:session][:username], params[:session][:password])
       if @user
         # Log the user in and redirect to the user's show page.
         log_in(@user)

         redirect_to questions_url

       else
         flash[:danger] = 'Invalid email/password combination' # Not quite right!
         render 'new'
       end
  end


  def destroy
    log_out
    redirect_to root_url

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_filter :set_user, :only => [:show, :edit, :update, :destroy]


  def show

  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(username: params[:user][:username], password: params[:user][:password])
     # @user = User.new(params[:user])
    if @user.save

      flash[:success] = "New user created"
      redirect_to questions_url

    else
      render 'new'
    end

  end

  private
  def set_user
    # @user = User.find(session[:id])
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username,  :password,)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  # before_filter :set_vote, :only => [:create, :edit, :update, :destroy]
  include SessionsHelper

  def new
    @vote = Vote.new
  end

  def create


    if params[:vote][:answer]
      @source = Answer.find(params[:vote][:answer].to_i)
      @question = @source.question

      voted = Vote.vote_only_once(current_user.id, @source)

    elsif params[:vote][:question]
      @source = Question.find(params[:vote][:question].to_i)
      @question = @source

      voted = Vote.vote_only_once(current_user.id, @source)

    end


    if voted
      redirect_to @question
    else

      @vote = Vote.create(source: @source, user: current_user)

      Question.vote_count(@question.id)

      redirect_to @question
    end




  end

  def destroy

    if params[:vote][:answer]
      @source = Answer.find(params[:vote][:answer].to_i)
      @question = @source.question

    elsif params[:vote][:question]
      @source = Question.find(params[:vote][:question].to_i)
      @question = @source
    end


    vote = @source.votes.first
    # if params[:vote][:question]

    vote.destroy
    redirect_to @question


  end

  private



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/display_best.html.erb
<h1>Stack No Flow</h1>

<div class="col-md-8">

<% if @user.questions.any? %>
<% @questions.each do |q|%>
<p>Title: <%= q.title %></p>
<p>Question text: <%= q.text %></p>



  <% if q.answers.any? %>
  <% q.answers.each do |a| %>

  <p>Answer: <%= a.text %><p>


    <% if a.best == true %>
    <p> Best answer </p>
    <% end %>

     <%= form_for(:answer, url: best_path)  do |f| %>

     <%= f.hidden_field :answer, :value => a.id %>

     <%= f.submit "Best", class: "btn btn-default" %>
     <% end %>

     <hr>

  <% end %>
  <% end %>

<% end %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CdOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= debug(params) if Rails.env.development? %>
    <ul class="nav navbar-nav">
      <li class="active"><li><%= link_to "Home", root_path %></li></li>
     <% if logged_in? %>
       <li><%= link_to "Log out", logout_path, method: :delete %></li>
       <li><%= link_to "Add Question", new_question_path %></li>
    <% else %>
      <li>
      <%= link_to "Log in", login_path%>
      </li>
    <% end %>

<%= yield %>

  </div>

</body>
</html>

app/views/questions/edit.html.erb
<% provide(:title, "Edit Question") %>
<h1>Edit your question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question) do |f| %>


      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.text_area :text, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>

      <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to "Sort by latest", root_path %></li>
  <li role="presentation"><%= link_to "Sort by votes", vote_path %></li>
  <li role="presentation"><%= link_to "Sort by trending", trending_path %></li>
</ul>


<h1>Stack No Flow</h1>
<table>
<% @questions.each do |x|%>
<p>Vote count(s): <%= x.vote_count %></p>
<a href="/questions/<%= x.id %>"><p>Title: <%= x.title %></p></a>
<p>Question text: <%= x.text %></p>
<p>Updated at: <%= x.updated_at %></p>

<%end%>
</table>

app/views/questions/new.html.erb
<% provide(:title, 'Ask a question') %>
<h1>Ask a Question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question) do |f| %>


      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :text %>
      <%= f.text_field :text, class: 'form-control' %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title%></h1>

<p>Text: <%= @question.text %></p>


<p>Author: <%= @question.user.username %></p>


 <% if logged_in? %>

 <p><div class="col-md-2">
 <%= form_for(@vote) do |f| %>

 <%= f.hidden_field :question, :value => @question.id %>

 <%= f.submit "Upvote", class: "btn btn-default" %>
 <% end %>

 </div>

 <p><div class="col-md-2">
 <%= form_for(:vote, url: downvote_path) do |f| %>

 <%= f.hidden_field :question, :value => @question.id %>

 <%= f.submit "Downvote", class: "btn btn-default" %>
 <% end %>


 </div></p>

 <% end %>

 <br>
 <br>

 <p>Votes: <%= @question.votes.count %></p>



 <% @question.comments.each do |x| %>

 <p>Comment(s):<%= x.text %></p>
 <% end %>


  <% @question.answers.each do |answer| %>
  <p>Answer(s):<%= answer.text %>

    <% if answer.best == true %>
    <p> Best answer </p>
    <% end %>

    <% if logged_in? %>

    <p>Votes: <%= answer.votes.count %></p>

     <%= form_for(@vote) do |f| %>

     <%= f.hidden_field :answer, :value => answer.id %>

     <%= f.submit "Upvote", class: "btn btn-default" %>
     <% end %>

      <%= form_for(:vote, url: downvote_path) do |f| %>

      <%= f.hidden_field :answer, :value => answer.id %>

      <%= f.submit "Downvote", class: "btn btn-default" %>
      <% end %>

    <hr>
  </p>
  <% end %>
  <% end %>

  <% if logged_in? %>

  <%= form_for(@comment) do |f| %>

  <%= f.label :Add_Comment %>
  <%= f.text_area :text, class: 'form-control' %>
  <%= f.hidden_field :question, :value => @question.id %>

  <%= f.submit "Comment", class: "btn btn-primary" %>
 <% end %>

 <br>
 <br>
 <hr>
 <br>

  <%= form_for(@answer) do |f| %>

  <%= f.label :Add_Answer %>
  <%= f.text_area :text, class: 'form-control' %>
  <%= f.hidden_field :question, :value => @question.id %>

  <%= f.submit "If you're genius, answer this", class: "btn btn-primary" %>
 <% end %>
 <% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(@user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>